"""Inventory, delivery, and payment checks; disposable local data only."""
import json, os, uuid, urllib.request, urllib.error, concurrent.futures
base=os.environ.get('DAIRY_TEST_URL','http://127.0.0.1:4101/api/v1')
assert base.startswith(('http://127.0.0.1:', 'http://localhost:'))
checks=[]
def call(method,path,data=None):
    h={'Content-Type':'application/json'}
    if token: h['Authorization']='Bearer '+token
    r=urllib.request.Request(base+path,headers=h,data=None if data is None else json.dumps(data).encode(),method=method)
    try:
        with urllib.request.urlopen(r,timeout=30) as x:return x.status,json.load(x)
    except urllib.error.HTTPError as e:return e.code,json.load(e)
def good(method,path,data=None):
    code,out=call(method,path,data);assert code in (200,201),(path,code,out);return out
def check(ok,label):assert ok,label;checks.append(label)
token=None
check(call('GET','/inventory')[0]==401,'private inventory')
token=good('POST','/auth/login',{'email':os.environ['DAIRY_TEST_EMAIL'],'password':os.environ['DAIRY_TEST_PASSWORD']})['accessToken']
u=uuid.uuid4().hex[:6]; uid=lambda:str(uuid.uuid4())
s=good('POST','/suppliers',{'name':'Prueba inventario '+u,'region':'Olancho'})
c=good('POST','/customers',{'name':'Prueba entregas '+u})
p=good('POST','/products',{'name':'Crema inventario '+u,'salePrice':'45','estimatedCost':'30','defaultSupplierId':s['id']})
r=good('POST','/rounds',{'name':'Inventario y cobros '+u,'opensAt':'2026-09-01T00:00:00Z','closesAt':'2026-10-01T00:00:00Z'})
line={'productId':p['id'],'supplierId':s['id'],'quantity':'2.5','unitPrice':'45'}
o=good('POST','/orders',{'roundId':r['id'],'customerId':c['id'],'items':[line]})
check(o['deliveryStatus']=='ORDERED' and o['paymentStatus']=='UNPAID','independent initial states')
d={'id':uid(),'version':o['version'],'deliveredAt':'2026-09-29T10:00:00Z','items':[{'orderItemId':o['items'][0]['id'],'quantity':'0.5'}]}
check(call('POST',f"/orders/{o['id']}/deliveries",d)[0]==400,'cannot deliver before receipt')
purchase=good('POST','/purchases',{'id':uid(),'roundId':r['id'],'supplierId':s['id'],'orderedAt':'2026-09-28T10:00:00Z','items':[{'productId':p['id'],'quantity':'5','quotedUnitCost':'30'}]})
good('POST',f"/purchases/{purchase['id']}/receipts",{'id':uid(),'version':purchase['version'],'receivedAt':'2026-09-28T15:00:00Z','invoice':'INV '+u,'globalDiscount':'0','items':[{'purchaseItemId':purchase['items'][0]['id'],'quantity':'5','unitCost':'30','unitDiscount':'0'}]})
def lot():return next(l for l in good('GET','/inventory') if l['productId']==p['id'])
check(lot()['available']=='2.5' and lot()['reserved']=='2.5','rounded and extra stock reserves only customer quantity')
o=good('POST',f"/orders/{o['id']}/deliveries",d)
check(o['deliveryStatus']=='PARTIAL' and o['paymentStatus']=='UNPAID','partial delivery remains unpaid')
retry=good('POST',f"/orders/{o['id']}/deliveries",d)
check(len(retry['deliveries'])==1 and lot()['onHand']=='4.5','delivery retry does not consume twice')
# Add stock to existing encargo, keeping delivered original line and exact total.
saved={k:o['items'][0][k] for k in ['id','productId','supplierId','quantity','unitPrice']}
o=good('PATCH',f"/orders/{o['id']}",{'version':o['version'],'items':[saved,{**line,'quantity':'0.5','source':'STOCK','totalAmount':'25'}]})
check(o['total']=='137.50' and lot()['available']=='2','extra stock attaches to encargo with premium half-pound total')
summary=good('GET',f"/rounds/{r['id']}/purchase-summary")
check(summary['totalQuantity']=='2.5','stock sale excluded from supplier request')
check(call('PATCH',f"/orders/{o['id']}",{'version':o['version'],'items':[{**line,'id':next(i['id'] for i in o['items'] if i['source']=='STOCK'),'quantity':'0.5','source':'STOCK'}]})[0]==400,'cannot erase delivered line')
pay={'id':uid(),'version':o['version'],'amount':'50','method':'CASH','paidAt':'2026-09-29T10:00:00Z'}
o=good('POST',f"/orders/{o['id']}/payments",pay)
check(o['paid']=='50.00' and o['balance']=='87.50' and o['paymentStatus']=='PARTIAL','partial abono computes balance')
check(good('POST',f"/orders/{o['id']}/payments",pay)['paid']=='50.00','payment retry is idempotent')
check(call('POST',f"/orders/{o['id']}/payments",{**pay,'id':uid(),'version':o['version'],'amount':'88'})[0]==400,'reject excess payment')
check(call('POST',f"/orders/{o['id']}/payments",{**pay,'id':uid(),'version':o['version'],'amount':'0'})[0]==400,'reject zero payment')
# Closing requires every encargo delivered and every free pound decided.
check(call('PATCH',f"/rounds/{r['id']}",{'status':'CLOSED'})[0]==409,'pending deliveries block a direct close')
state=good('GET',f"/rounds/{r['id']}/closing")
check(len(state['pendingDeliveries'])==1 and state['leftovers'][0]['available']=='2','closing lists pending deliveries and leftovers')
check(call('POST',f"/rounds/{r['id']}/close",{'decisions':[]})[0]==409,'guided close is blocked by pending deliveries')
d2={'id':uid(),'version':o['version'],'deliveredAt':'2026-09-29T12:00:00Z','items':[{'orderItemId':i['id'],'quantity':str(float(i['quantity'])-float(i['deliveredQuantity']))} for i in o['items']]}
o=good('POST',f"/orders/{o['id']}/deliveries",d2)
leftover=good('GET',f"/rounds/{r['id']}/closing")['leftovers'][0]['receiptItemId']
check(call('POST',f"/rounds/{r['id']}/close",{'decisions':[{'receiptItemId':leftover,'reason':'KEEP','quantity':'1.5'}]})[0]==400,'every leftover pound needs a destination')
good('POST',f"/rounds/{r['id']}/close",{'decisions':[{'receiptItemId':leftover,'reason':'KEEP','quantity':'2'}]})
check(next(x for x in good('GET','/rounds') if x['id']==r['id'])['status']=='CLOSED','kept stock closes the cycle')
check(o['deliveryStatus']=='DELIVERED' and o['paymentStatus']=='PARTIAL','delivered but unpaid remainder in closed cycle')
o=good('POST',f"/orders/{o['id']}/payments",{**pay,'id':uid(),'version':o['version'],'amount':'87.50','method':'TRANSFER'})
check(o['paymentStatus']=='PAID' and o['balance']=='0.00','full payment automatically marks paid')
o=good('POST',f"/orders/{o['id']}/payments/{pay['id']}/void",{'reason':'Corrección de prueba'})
check(o['paymentStatus']=='PARTIAL' and o['balance']=='50.00' and len(o['payments'])==2,'void preserves history and recalculates balance')
check(lot()['reserved']=='0' and lot()['onHand']=='2','delivery reduces on-hand, leaves extras')
r2=good('POST','/rounds',{'name':'Siguiente ciclo '+u,'opensAt':'2026-09-29T00:00:00Z','closesAt':'2026-10-02T00:00:00Z'})
body={'roundId':r2['id'],'customerId':c['id'],'items':[{**line,'source':'STOCK','quantity':'1.5'}]}
with concurrent.futures.ThreadPoolExecutor(max_workers=2) as pool:codes=list(pool.map(lambda _:call('POST','/orders',body)[0],range(2)))
check(sorted(codes)==[201,409],'concurrent stock buyers cannot oversell across cycles')
check(lot()['available']=='0.5','prior cycle lot remains available in next cycle')
w={'id':uid(),'receiptItemId':lot()['id'],'quantity':'0.5','reason':'SAMPLE'}
good('POST','/inventory/withdrawals',w);good('POST','/inventory/withdrawals',w)
check(lot()['available']=='0','sample withdrawal idempotent and reduces free stock')
check(call('POST','/inventory/withdrawals',{**w,'id':uid()})[0]==400,'cannot withdraw reserved inventory')
# New demand must still be purchased after extras were sold/withdrawn.
new=good('POST','/orders',{'roundId':r2['id'],'customerId':c['id'],'items':[{**line,'quantity':'0.5'}]})
summary=good('GET',f"/rounds/{r2['id']}/purchase-summary")
check(summary['groups'][0]['items'][0]['pendingToBuy']=='0.5','new preorder shortage excludes consumed old extras')
incoming=good('POST','/purchases',{'id':uid(),'roundId':r2['id'],'supplierId':s['id'],'orderedAt':'2026-09-29T14:00:00Z','items':[{'productId':p['id'],'quantity':'1','quotedUnitCost':'30'}]})
summary=good('GET',f"/rounds/{r2['id']}/purchase-summary")
check(summary['groups'][0]['items'][0]['pendingToBuy']=='0','pending supplier purchase prevents buying twice')
check(lot()['available']=='0','unreceived purchase is not sellable inventory')
# Purchases are editable only while their cycle is open and before any invoice.
item=lambda q,prod=None:{'productId':(prod or p)['id'],'quantity':q,'quotedUnitCost':'30'}
purchase=next(x for x in good('GET',f"/purchases?roundId={r['id']}") if x['id']==purchase['id'])
good('PATCH',f"/rounds/{r['id']}",{'status':'OPEN'})
check(call('PATCH',f"/purchases/{purchase['id']}",{'version':purchase['version'],'items':[item('6')]})[0]==409,'invoiced purchase cannot be edited')
p2=good('POST','/products',{'name':'Quesillo edición '+u,'salePrice':'60','estimatedCost':'40','defaultSupplierId':s['id']})
pe=good('POST','/purchases',{'id':uid(),'roundId':r['id'],'supplierId':s['id'],'orderedAt':'2026-09-29T10:00:00Z','items':[item('2')]})
edited=good('PATCH',f"/purchases/{pe['id']}",{'version':pe['version'],'items':[item('3'),item('2',p2)]})
check(edited['version']==pe['version']+1 and len(edited['items'])==2,'open cycle allows growing and adding lines before invoice')
check(call('PATCH',f"/purchases/{pe['id']}",{'version':pe['version'],'items':[item('4')]})[0]==409,'stale purchase version is rejected')
edited=good('PATCH',f"/purchases/{pe['id']}",{'version':edited['version'],'items':[item('3')]})
check(len(edited['items'])==1,'product can be removed before invoice')
edited=good('POST',f"/purchases/{pe['id']}/receipts",{'id':uid(),'version':edited['version'],'receivedAt':'2026-09-29T16:00:00Z','invoice':'INV2 '+u,'globalDiscount':'0','items':[{'purchaseItemId':edited['items'][0]['id'],'quantity':'3','unitCost':'31','unitDiscount':'0'}]})
check(sum(float(x['quantity']) for rc in edited['receipts'] for x in rc['items'])==3,'edited purchase can be received')
check(call('PATCH',f"/purchases/{pe['id']}",{'version':edited['version'],'items':[item('5')]})[0]==409,'purchase locks once invoiced')
pf=good('POST','/purchases',{'id':uid(),'roundId':r['id'],'supplierId':s['id'],'orderedAt':'2026-09-29T11:00:00Z','items':[item('1')]})
state=good('GET',f"/rounds/{r['id']}/closing")
good('POST',f"/rounds/{r['id']}/close",{'decisions':[{'receiptItemId':l['receiptItemId'],'reason':'KEEP','quantity':l['available']} for l in state['leftovers']]})
check(call('PATCH',f"/purchases/{pf['id']}",{'version':pf['version'],'items':[item('2')]})[0]==409,'closed cycle blocks purchase edits')
# Walk-in sales use free stock of any cycle, even closed, and count in the lot's cycle.
free=lambda:sum(float(l['available']) for l in good('GET','/inventory') if l['productId']==p['id'])
before=free()
sale={'id':uid(),'soldAt':'2026-09-30T10:00:00Z','items':[{'productId':p['id'],'quantity':'1','unitPrice':'48'}],'payment':{'amount':'48.00','method':'CASH'}}
sold=good('POST','/sales',sale)
check(sold['kind']=='DIRECT' and sold['deliveryStatus']=='DELIVERED' and sold['paymentStatus']=='PAID','walk-in sale is delivered and paid on the spot')
check(sold['roundId']==r['id'] and free()==before-1,'sale consumes free stock and counts in the lot cycle')
check(good('POST','/sales',sale)['id']==sold['id'] and free()==before-1,'sale retry is idempotent')
check(all(x['id']!=sold['id'] for x in good('GET',f"/orders?roundId={r['id']}")),'walk-in sales stay out of the encargo list')
check(any(x['id']==sold['id'] for x in good('GET','/sales')),'walk-in sales are listed apart')
check(any(x['id']==sold['id'] for x in good('GET',f"/sales?roundId={r['id']}")) and all(x['roundId']==r['id'] for x in good('GET',f"/sales?roundId={r['id']}")),'walk-in sales list by cycle')
check(call('POST','/sales',{**sale,'id':uid(),'items':[{**sale['items'][0],'quantity':'500'}]})[0]==400,'cannot sell more than free stock')
check(call('PATCH',f"/orders/{sold['id']}",{'version':sold['version'],'notes':'x'})[0]==400,'walk-in sales are not edited as encargos')
unpaid={'id':uid(),'soldAt':sale['soldAt'],'items':[{**sale['items'][0],'quantity':'0.5'}]}
credit=good('POST','/sales',unpaid)
check(credit['paymentStatus']=='UNPAID' and credit['balance']=='24.00','unpaid walk-in sale becomes a debt')
# Losses and samples at close are absorbed cost of the cycle that bought them.
r3=good('POST','/rounds',{'name':'Cierre con merma '+u,'opensAt':'2026-09-29T00:00:00Z','closesAt':'2026-10-03T00:00:00Z'})
buy=good('POST','/purchases',{'id':uid(),'roundId':r3['id'],'supplierId':s['id'],'orderedAt':'2026-09-29T14:00:00Z','items':[{'productId':p['id'],'quantity':'3','quotedUnitCost':'40'}]})
good('POST',f"/purchases/{buy['id']}/receipts",{'id':uid(),'version':buy['version'],'receivedAt':'2026-09-29T15:00:00Z','invoice':'INV3 '+u,'globalDiscount':'0','items':[{'purchaseItemId':buy['items'][0]['id'],'quantity':'3','unitCost':'40','unitDiscount':'0'}]})
lot3=good('GET',f"/rounds/{r3['id']}/closing")['leftovers'][0]['receiptItemId']
good('POST',f"/rounds/{r3['id']}/close",{'decisions':[{'receiptItemId':lot3,'reason':'LOSS','quantity':'2'},{'receiptItemId':lot3,'reason':'SAMPLE','quantity':'1'}]})
cyc=next(c for c in good('GET','/statistics')['cycles'] if c['id']==r3['id'])
check(cyc['absorbed']['loss']['cost']=='80.00' and cyc['absorbed']['sample']['pounds']=='1' and cyc['absorbed']['total']=='120.00','close records loss and samples as absorbed cost')
check(call('POST',f"/rounds/{r3['id']}/close",{'decisions':[]})[0]==409,'a closed cycle cannot be closed again')
# An encargo bought from another supplier is still reserved and deliverable,
# without taking lots from a supplier's own encargos first.
sA=good('POST','/suppliers',{'name':'Proveedor A '+u,'region':'Olancho'})
sB=good('POST','/suppliers',{'name':'Proveedor B '+u,'region':'Sur'})
pq=good('POST','/products',{'name':'Quesillo cruzado '+u,'salePrice':'75','estimatedCost':'50','defaultSupplierId':sA['id']})
r4=good('POST','/rounds',{'name':'Proveedor cruzado '+u,'opensAt':'2026-09-29T00:00:00Z','closesAt':'2026-10-04T00:00:00Z'})
oa=good('POST','/orders',{'roundId':r4['id'],'customerId':c['id'],'items':[{'productId':pq['id'],'supplierId':sA['id'],'quantity':'2','unitPrice':'75'}]})
ob=good('POST','/orders',{'roundId':r4['id'],'customerId':c['id'],'items':[{'productId':pq['id'],'supplierId':sB['id'],'quantity':'1','unitPrice':'75'}]})
bb=good('POST','/purchases',{'id':uid(),'roundId':r4['id'],'supplierId':sB['id'],'orderedAt':'2026-09-29T14:00:00Z','items':[{'productId':pq['id'],'quantity':'3','quotedUnitCost':'50'}]})
good('POST',f"/purchases/{bb['id']}/receipts",{'id':uid(),'version':bb['version'],'receivedAt':'2026-09-29T15:00:00Z','invoice':'INV4 '+u,'globalDiscount':'0','items':[{'purchaseItemId':bb['items'][0]['id'],'quantity':'3','unitCost':'50','unitDiscount':'0'}]})
byId={o['id']:o for o in good('GET',f"/orders?roundId={r4['id']}")}
check(byId[ob['id']]['items'][0]['reservedQuantity']=='1','supplier own encargo keeps its lot first')
check(byId[oa['id']]['items'][0]['reservedQuantity']=='2','encargo bought from another supplier is reserved')
oa=byId[oa['id']]
oa=good('POST',f"/orders/{oa['id']}/deliveries",{'id':uid(),'version':oa['version'],'deliveredAt':'2026-09-29T16:00:00Z','items':[{'orderItemId':oa['items'][0]['id'],'quantity':'2'}]})
check(oa['deliveryStatus']=='DELIVERED','cross-supplier encargo can be delivered')
# Walk-in sales use stock of any cycle (oldest first), count in the chosen
# cycle, and stay editable while that cycle is open.
pw=good('POST','/products',{'name':'Venta libre '+u,'salePrice':'45','estimatedCost':'30','defaultSupplierId':s['id']})
rOld=good('POST','/rounds',{'name':'Sobrante anterior '+u,'opensAt':'2026-09-20T00:00:00Z','closesAt':'2026-09-27T00:00:00Z'})
bo=good('POST','/purchases',{'id':uid(),'roundId':rOld['id'],'supplierId':s['id'],'orderedAt':'2026-09-21T10:00:00Z','items':[{'productId':pw['id'],'quantity':'2','quotedUnitCost':'28'}]})
good('POST',f"/purchases/{bo['id']}/receipts",{'id':uid(),'version':bo['version'],'receivedAt':'2026-09-21T12:00:00Z','invoice':'OLD '+u,'globalDiscount':'0','items':[{'purchaseItemId':bo['items'][0]['id'],'quantity':'2','unitCost':'28','unitDiscount':'0'}]})
r5=good('POST','/rounds',{'name':'Ventas editables '+u,'opensAt':'2026-09-29T00:00:00Z','closesAt':'2026-10-05T00:00:00Z'})
b5=good('POST','/purchases',{'id':uid(),'roundId':r5['id'],'supplierId':s['id'],'orderedAt':'2026-09-29T14:00:00Z','items':[{'productId':pw['id'],'quantity':'4','quotedUnitCost':'30'}]})
good('POST',f"/purchases/{b5['id']}/receipts",{'id':uid(),'version':b5['version'],'receivedAt':'2026-09-29T15:00:00Z','invoice':'INV5 '+u,'globalDiscount':'0','items':[{'purchaseItemId':b5['items'][0]['id'],'quantity':'4','unitCost':'30','unitDiscount':'0'}]})
freeIn=lambda rid:sum(float(l['available']) for l in good('GET','/inventory') if l['roundId']==rid and l['productId']==pw['id'])
line5=lambda q:[{'productId':pw['id'],'quantity':q,'unitPrice':'45'}]
sale5=good('POST','/sales',{'id':uid(),'roundId':r5['id'],'soldAt':'2026-09-30T10:00:00Z','items':line5('3'),'payment':{'amount':'60.00','method':'CASH'}})
check(sale5['roundId']==r5['id'] and freeIn(rOld['id'])==0 and freeIn(r5['id'])==3,'sale counts in the chosen cycle and uses older leftover stock first')
cy5=next(x for x in good('GET','/statistics')['cycles'] if x['id']==r5['id'])
check(cy5['costing']['costSources']['lot']=='3','sale is costed with the real lots it took')
sale5=good('PATCH',f"/sales/{sale5['id']}",{'version':sale5['version'],'items':line5('4')})
check(sale5['total']=='180.00' and freeIn(r5['id'])==2 and sale5['deliveryStatus']=='DELIVERED','editing a sale re-delivers and adjusts stock')
check(call('PATCH',f"/sales/{sale5['id']}",{'version':sale5['version'],'items':line5('1')})[0]==400,'edit cannot drop below what was collected')
check(call('PATCH',f"/sales/{sale5['id']}",{'version':sale5['version'],'items':line5('9')})[0]==400 and freeIn(r5['id'])==2,'edit beyond available stock is rejected intact')
check(call('DELETE',f"/sales/{sale5['id']}?version={sale5['version']-1}")[0]==409,'stale sale version cannot be deleted')
good('DELETE',f"/sales/{sale5['id']}?version={sale5['version']}")
check(freeIn(r5['id'])==4 and freeIn(rOld['id'])==2 and all(x['id']!=sale5['id'] for x in good('GET',f"/sales?roundId={r5['id']}")),'deleting a sale returns its stock')
sale6=good('POST','/sales',{'id':uid(),'roundId':r5['id'],'soldAt':'2026-09-30T11:00:00Z','items':line5('1')})
lots5=good('GET',f"/rounds/{r5['id']}/closing")['leftovers']
good('POST',f"/rounds/{r5['id']}/close",{'decisions':[{'receiptItemId':l['receiptItemId'],'reason':'KEEP','quantity':l['available']} for l in lots5]})
check(call('PATCH',f"/sales/{sale6['id']}",{'version':sale6['version'],'items':line5('2')})[0]==409,'closed cycle blocks sale edits')
check(call('DELETE',f"/sales/{sale6['id']}?version={sale6['version']}")[0]==409,'closed cycle blocks sale deletion')
r7=good('POST','/rounds',{'name':'Después del cierre '+u,'opensAt':'2026-10-06T00:00:00Z','closesAt':'2026-10-12T00:00:00Z'})
sale7=good('POST','/sales',{'id':uid(),'roundId':r7['id'],'soldAt':'2026-10-06T10:00:00Z','items':line5('2')})
check(sale7['roundId']==r7['id'] and freeIn(r5['id'])+freeIn(rOld['id'])==3,'stock kept at closing is sold in a later cycle')
# Accounting: fixed categories, manual and automatic movements, owners.
cats=good('GET','/finance/categories')
key=lambda k:next(x for x in cats if x['systemKey']==k)
check(key('SALE')['automatic'] and not key('PROFIT_DISTRIBUTION')['inResult'],'system categories flagged')
cat=good('POST','/finance/categories',{'name':'Prueba cat '+u,'kind':'EXPENSE'})
check(call('POST','/finance/categories',{'name':'prueba CAT '+u,'kind':'EXPENSE'})[0]==409,'duplicate category rejected')
check(call('PATCH',f"/finance/categories/{key('SALE')['id']}",{'active':False})[0]==400,'system category cannot be disabled')
good('PATCH',f"/finance/categories/{cat['id']}",{'name':'Prueba renombrada '+u})
mv=lambda **k:{'id':uid(),'kind':'EXPENSE','date':'2026-09-30T12:00:00Z','amount':'25','categoryId':cat['id'],'description':'Bolsas '+u,**k}
check(call('POST','/finance/movements',mv(categoryId=key('PRODUCT_PURCHASE')['id']))[0]==400,'product purchases only come from invoices')
check(call('POST','/finance/movements',mv(paidBy='ARIEL'))[0]==400,'personal payment needs a decision')
check(call('POST','/finance/movements',{**mv(),'kind':'INCOME','categoryId':key('OWNER_CONTRIBUTION')['id']})[0]==400,'contribution needs an owner')
before=good('GET','/finance/summary?month=2026-09')
bag=good('POST','/finance/movements',mv(paidBy='ARIEL',personalMode='REIMBURSE',roundId=r5['id']))
gift=good('POST','/finance/movements',mv(paidBy='MARIA',personalMode='CONTRIBUTE',amount='10'))
check(call('DELETE',f"/finance/categories/{cat['id']}")[0]==409,'used category cannot be deleted')
led=good('GET','/finance/ledger?month=2026-09')
check(any(l['id']==bag['id'] for l in led['owed']),'owner reimbursement is listed as owed')
check(any(l['source']=='INVOICE' and u in l['description'] for l in led['lines']) and any(l['source']=='PAYMENT' for l in led['lines']),'invoices and cobros enter the ledger')
after=good('GET','/finance/summary?month=2026-09')
dec=lambda a,b,f:round(float(f(b))-float(f(a)),2)
check(dec(before,after,lambda x:x['monthly']['expense'])==35,'personal payments are business expenses')
check(dec(before,after,lambda x:x['monthly']['cashExpected'])==0,'owner-paid expenses do not leave the till')
check(dec(before,after,lambda x:x['allTime']['contributed']['MARIA'])==10 and dec(before,after,lambda x:x['allTime']['owedToOwners']['ARIEL'])==25,'gift adds value, reimbursement is owed')
check(next(c for c in after['cycleExpenses'] if c['id']==r5['id'])['expenses']=='25.00','cycle expenses are tracked')
bag=good('POST',f"/finance/movements/{bag['id']}/reimburse",{'version':bag['version'],'date':'2026-10-01T12:00:00Z'})
check(not any(l['id']==bag['id'] for l in good('GET','/finance/ledger?month=2026-09')['owed']),'reimbursed payment leaves owed list')
rec=good('POST','/finance/recurring',{'description':'Internet '+u,'categoryId':cat['id'],'amount':'300','frequency':'MONTHLY','day':3,'startsOn':'2026-08-01T06:00:00Z'})
pend=[l for l in good('GET','/finance/ledger?month=2026-09')['pending'] if l['recurringId']==rec['id']]
check(len(pend)==3,'recurring periods generated up to today')
check(len([l for l in good('GET','/finance/ledger?month=2026-09')['pending'] if l['recurringId']==rec['id']])==3,'recurring generation is idempotent')
good('POST',f"/finance/movements/{pend[0]['id']}/pay",{'version':pend[0]['version'],'date':'2026-08-03T12:00:00Z','amount':'310','method':'TRANSFER'})
good('DELETE',f"/finance/movements/{pend[1]['id']}?version={pend[1]['version']}")
rec=next(x for x in good('GET','/finance/recurring') if x['id']==rec['id'])
check(rec['pendingCount']==1,'paid and skipped periods leave one pending')
rec=good('PATCH',f"/finance/recurring/{rec['id']}",{'version':rec['version'],'description':'Internet '+u,'categoryId':cat['id'],'amount':'320','frequency':'MONTHLY','day':3,'startsOn':'2026-08-01T06:00:00Z','active':False})
left=[l for l in good('GET','/finance/ledger?month=2026-10')['pending'] if l['recurringId']==rec['id']]
check(len(left)==1 and left[0]['amount']=='320.00','template edits reach pending periods only')
avail=float(good('GET','/finance/summary')['allTime']['available'])
check(call('POST','/finance/distributions',{'id':uid(),'date':'2026-10-01T12:00:00Z','ariel':f"{max(avail,0)+1:.2f}",'maria':'0'})[0]==400,'cannot distribute beyond available profit')
if avail<20:good('POST','/finance/movements',{'id':uid(),'kind':'INCOME','date':'2026-10-01T12:00:00Z','amount':f"{20-avail:.2f}",'categoryId':next(x for x in cats if x['name']=='Otros ingresos')['id'],'description':'Ajuste prueba '+u})
s0=good('GET','/finance/summary')
gid=uid();parts=good('POST','/finance/distributions',{'id':gid,'date':'2026-10-01T12:00:00Z','ariel':'5','maria':'5'})
s1=good('GET','/finance/summary')
check(len(parts)==2 and dec(s0,s1,lambda x:x['allTime']['available'])==-10 and dec(s0,s1,lambda x:x['allTime']['result'])==0,'distribution reduces available, not profit')
good('DELETE',f"/finance/movements/{parts[0]['id']}?version={parts[0]['version']}")
check(dec(s0,good('GET','/finance/summary'),lambda x:x['allTime']['distributed'])==0,'deleting a distribution removes both halves')
# Cobrado en el ciclo 2, sin producto; se compra y entrega en el ciclo 3.
rq=good('POST','/products',{'name':'Requesón '+u,'salePrice':'80','estimatedCost':'45','defaultSupplierId':s['id']})
c2=good('POST','/rounds',{'name':'Ciclo 2 '+u,'opensAt':'2026-09-20T00:00:00Z','closesAt':'2026-09-27T00:00:00Z'})
c3=good('POST','/rounds',{'name':'Ciclo 3 '+u,'opensAt':'2026-09-27T00:00:00Z','closesAt':'2026-10-04T00:00:00Z'})
oc=good('POST','/orders',{'roundId':c2['id'],'customerId':c['id'],'items':[{'productId':rq['id'],'supplierId':s['id'],'quantity':'1','unitPrice':'80'}]})
oc=good('POST',f"/orders/{oc['id']}/payments",{'id':uid(),'version':oc['version'],'amount':'80','method':'CASH','paidAt':'2026-09-22T12:00:00Z'})
check(len(good('GET',f"/rounds/{c2['id']}/closing")['pendingDeliveries'])==1,'unsupplied encargo holds its cycle open')
ln=oc['items'][0]['id']
check(call('POST',f"/orders/{oc['id']}/items/{ln}/carry",{'version':oc['version'],'roundId':c2['id']})[0]==400,'cannot carry to its own cycle')
oc=good('POST',f"/orders/{oc['id']}/items/{ln}/carry",{'version':oc['version'],'roundId':c3['id']})
st2=good('GET',f"/rounds/{c2['id']}/closing")
check(not st2['pendingDeliveries'] and st2['carriedOut'][0]['toRound']==c3['name'],'carried line no longer blocks the paid cycle')
good('POST',f"/rounds/{c2['id']}/close",{'decisions':[]})
rows=lambda rid:[i for g in good('GET',f"/rounds/{rid}/purchase-summary")['groups'] for i in g['items'] if i['productId']==rq['id']]
check(not rows(c2['id']) and rows(c3['id'])[0]['pendingToBuy']=='1','carried pounds move to the next supplier list')
check(call('POST',f"/orders/{oc['id']}/items/{ln}/carry",{'version':oc['version'],'roundId':None})[0]==400,'closed cycle cannot take back a pending line')
b3=good('POST','/purchases',{'id':uid(),'roundId':c3['id'],'supplierId':s['id'],'orderedAt':'2026-09-28T10:00:00Z','items':[{'productId':rq['id'],'quantity':'3','quotedUnitCost':'50'}]})
good('POST',f"/purchases/{b3['id']}/receipts",{'id':uid(),'version':b3['version'],'receivedAt':'2026-09-28T12:00:00Z','invoice':'REQ '+u,'globalDiscount':'0','items':[{'purchaseItemId':b3['items'][0]['id'],'quantity':'3','unitCost':'50','unitDiscount':'0'}]})
carried=good('GET',f"/orders/carried?roundId={c3['id']}")
check(len(carried)==1 and carried[0]['items'][0]['reservedQuantity']=='1','next cycle reserves the carried pound')
st3=good('GET',f"/rounds/{c3['id']}/closing")
check(st3['pendingDeliveries'][0]['fromRound']==c2['name'] and st3['leftovers'][0]['available']=='2','next cycle must deliver it and only the rest is free')
oc=carried[0]
oc=good('POST',f"/orders/{oc['id']}/deliveries",{'id':uid(),'version':oc['version'],'deliveredAt':'2026-09-28T15:00:00Z','items':[{'orderItemId':ln,'quantity':'1'}]})
check(oc['deliveryStatus']=='DELIVERED' and oc['paymentStatus']=='PAID' and oc['total']=='80.00','delivered without charging again')
cy=next(x for x in good('GET','/statistics')['cycles'] if x['id']==c2['id'])
check(cy['sales']=='80.00' and cy['result']=='30.00','paid cycle keeps the sale with the real cost of the later lot')
# Envío opcional: retira, gratis o con costo; el ciclo suma envíos y resta su combustible.
c4=good('POST','/rounds',{'name':'Envíos '+u,'opensAt':'2026-10-01T00:00:00Z','closesAt':'2026-10-10T00:00:00Z'})
item4={'productId':rq['id'],'supplierId':s['id'],'quantity':'2','unitPrice':'80'}
check(call('POST','/orders',{'roundId':c4['id'],'customerId':c['id'],'delivery':'PICKUP','shippingFee':'30','items':[item4]})[0]==400,'pickup cannot carry a shipping fee')
od=good('POST','/orders',{'roundId':c4['id'],'customerId':c['id'],'delivery':'DELIVERY','shippingFee':'40','items':[item4]})
check(od['total']=='200.00' and od['productTotal']=='160.00' and od['shippingFee']=='40.00','shipping adds to the encargo total')
od=good('POST',f"/orders/{od['id']}/payments",{'id':uid(),'version':od['version'],'amount':'200','method':'CASH','paidAt':'2026-10-02T12:00:00Z'})
check(od['paymentStatus']=='PAID' and od['balance']=='0.00','paying product and shipping settles it')
free=good('POST','/orders',{'roundId':c4['id'],'customerId':c['id'],'delivery':'DELIVERY','items':[item4]})
check(free['total']=='160.00' and free['delivery']=='DELIVERY','free delivery adds nothing')
od=good('PATCH',f"/orders/{od['id']}",{'version':od['version'],'delivery':'PICKUP'})
check(od['total']=='160.00' and od['credit']=='40.00','switching to pickup drops the fee and leaves credit')
od=good('PATCH',f"/orders/{od['id']}",{'version':od['version'],'delivery':'DELIVERY','shippingFee':'40'})
fuel=next(x for x in good('GET','/finance/categories') if x['systemKey']=='TRANSPORT')
good('POST','/finance/movements',{'id':uid(),'kind':'EXPENSE','date':'2026-10-02T12:00:00Z','amount':'15','categoryId':fuel['id'],'description':'Gasolina reparto '+u,'roundId':c4['id']})
cy=next(x for x in good('GET','/statistics')['cycles'] if x['id']==c4['id'])
check(cy['shipping']=='40.00' and cy['deliveries']==2 and cy['fuel']=='15.00' and cy['expenses']=='15.00','cycle reports shipping charged against fuel')
check(cy['productResult'] is not None and round(float(cy['result'])-float(cy['productResult']),2)==25,'cycle result adds shipping and subtracts its expenses')
# Cuenta del cliente: anticipo, uso en encargos, pago de más y devolución.
ca=good('POST','/customers',{'name':'Cuenta '+u})
acct=lambda:good('GET',f"/customers/{ca['id']}/account")
fin0=good('GET','/finance/summary?month=2026-10')['allTime']
dep=uid();good('POST',f"/customers/{ca['id']}/account/deposits",{'id':dep,'amount':'1000','method':'TRANSFER','date':'2026-10-02T12:00:00Z'})
good('POST',f"/customers/{ca['id']}/account/deposits",{'id':dep,'amount':'1000','method':'TRANSFER','date':'2026-10-02T12:00:00Z'})
check(acct()['balance']=='1000.00','advance is held once in the customer account')
oa1=good('POST','/orders',{'roundId':c4['id'],'customerId':ca['id'],'delivery':'DELIVERY','shippingFee':'40','items':[item4]})
check(call('POST',f"/orders/{oa1['id']}/apply-credit",{'id':uid(),'version':oa1['version'],'amount':'250','date':'2026-10-03T12:00:00Z'})[0]==400,'credit cannot exceed the order balance')
pay=uid();oa1=good('POST',f"/orders/{oa1['id']}/apply-credit",{'id':pay,'version':oa1['version'],'amount':'200','date':'2026-10-03T12:00:00Z'})
check(oa1['paymentStatus']=='PAID' and acct()['balance']=='800.00','account pays the encargo and is discounted')
fin1=good('GET','/finance/summary?month=2026-10')['allTime']
check(round(float(fin1['income'])-float(fin0['income']),2)==1000,'money counts once: at deposit, not when used')
row=next(r for r in good('GET','/collections')['customers'] if r['customer']['id']==ca['id'])
check(row['account']=='800.00' and row['owed']=='0.00','collections shows money held for the customer')
oa1=good('POST',f"/orders/{oa1['id']}/payments/{pay}/void",{'reason':'prueba'})
check(acct()['balance']=='1000.00' and oa1['balance']=='200.00','voiding a credit payment returns the credit')
check(call('POST',f"/customers/{ca['id']}/account/refunds",{'id':uid(),'amount':'1500','method':'CASH','date':'2026-10-04T12:00:00Z'})[0]==400,'cannot refund more than the credit')
row=next(r for r in good('GET','/collections')['customers'] if r['customer']['id']==ca['id'])
check(row['owed']=='200.00' and row['orders'][0]['id']==oa1['id'],'collections lists what the customer owes')
oa1=good('POST',f"/orders/{oa1['id']}/payments",{'id':uid(),'version':oa1['version'],'amount':'250','method':'CASH','paidAt':'2026-10-04T12:00:00Z','excessToAccount':True})
check(oa1['paymentStatus']=='PAID' and acct()['balance']=='1050.00','paying over the balance keeps the rest as credit')
check(call('POST',f"/orders/{oa1['id']}/payments",{'id':uid(),'version':oa1['version'],'amount':'10','method':'CASH','paidAt':'2026-10-04T12:00:00Z'})[0]==400,'no payment on a settled order')
oa1=good('PATCH',f"/orders/{oa1['id']}",{'version':oa1['version'],'delivery':'PICKUP'})
oa1=good('POST',f"/orders/{oa1['id']}/credit-to-account",{'id':uid(),'version':oa1['version']})
check(oa1['credit']=='0.00' and oa1['paymentStatus']=='PAID' and acct()['balance']=='1090.00','order excess moves to the account')
good('POST',f"/customers/{ca['id']}/account/refunds",{'id':uid(),'amount':'90','method':'CASH','date':'2026-10-05T12:00:00Z'})
fin2=good('GET','/finance/summary?month=2026-10')['allTime']
check(acct()['balance']=='1000.00' and round(float(fin2['cashExpected'])-float(fin1['cashExpected']),2)==160,'refund leaves the till; cash = +250 paid −90 refunded')
# Vencimiento: duración del producto desde la recepción, o fecha del empaque.
import datetime as _dt
now=_dt.datetime.now(_dt.timezone.utc)
iso=lambda d:d.strftime('%Y-%m-%dT%H:%M:%SZ')
fresh=good('POST','/products',{'name':'Cuajada '+u,'salePrice':'60','estimatedCost':'35','defaultSupplierId':s['id'],'shelfLifeDays':3,'warnDays':1})
honey=good('POST','/products',{'name':'Miel '+u,'salePrice':'150','estimatedCost':'90','defaultSupplierId':s['id']})
check(fresh['shelfLifeDays']==3 and honey['shelfLifeDays'] is None,'products keep their shelf life')
check(call('PATCH',f"/products/{honey['id']}",{'shelfLifeDays':0})[0]==400,'shelf life must be at least a day')
c5=good('POST','/rounds',{'name':'Vencimientos '+u,'opensAt':iso(now-_dt.timedelta(days=3)),'closesAt':iso(now+_dt.timedelta(days=5))})
b5x=good('POST','/purchases',{'id':uid(),'roundId':c5['id'],'supplierId':s['id'],'orderedAt':iso(now-_dt.timedelta(days=3)),'items':[{'productId':fresh['id'],'quantity':'2','quotedUnitCost':'35'},{'productId':honey['id'],'quantity':'2','quotedUnitCost':'90'},{'productId':rq['id'],'quantity':'1','quotedUnitCost':'45'}]})
pi={i['productId']:i['id'] for i in b5x['items']}
printed=(now+_dt.timedelta(days=200)).strftime('%Y-%m-%dT18:00:00Z')
good('POST',f"/purchases/{b5x['id']}/receipts",{'id':uid(),'version':b5x['version'],'receivedAt':iso(now-_dt.timedelta(days=2)),'invoice':'VEN '+u,'globalDiscount':'0','items':[
  {'purchaseItemId':pi[fresh['id']],'quantity':'2','unitCost':'35','unitDiscount':'0'},
  {'purchaseItemId':pi[honey['id']],'quantity':'2','unitCost':'90','unitDiscount':'0','expiresAt':printed},
  {'purchaseItemId':pi[rq['id']],'quantity':'1','unitCost':'45','unitDiscount':'0'}]})
lots5={l['productId']:l for l in good('GET','/inventory') if l['roundId']==c5['id']}
check(lots5[fresh['id']]['daysLeft']==1 and lots5[fresh['id']]['expiryStatus']=='SOON','fresh lot counts its days from receipt and warns')
check(lots5[honey['id']]['expiresAt'].startswith(printed[:10]) and lots5[honey['id']]['expiryStatus']=='OK','printed expiry is kept')
check(lots5[rq['id']]['expiresAt'] is None,'products without shelf life have no expiry')
good('PATCH',f"/inventory/lots/{lots5[fresh['id']]['id']}/expiry",{'expiresAt':iso(now-_dt.timedelta(days=2))})
check(next(l for l in good('GET','/inventory') if l['id']==lots5[fresh['id']]['id'])['expiryStatus']=='EXPIRED','lot expiry can be corrected')
# Datos de pago editables.
pinfo=good('GET','/settings/paymentInfo')
check('BAC Credomatic' in pinfo['value'],'payment details are seeded')
check(call('GET','/settings/otra')[0]==404,'only known settings are exposed')
check(call('PATCH','/settings/paymentInfo',{'version':pinfo['version']+5,'value':'x'})[0]==409,'stale payment details edit is rejected')
edited=good('PATCH','/settings/paymentInfo',{'version':pinfo['version'],'value':pinfo['value']+'\n\nPrueba '+u})
check(edited['version']==pinfo['version']+1 and edited['value'].endswith(u),'payment details can be edited')
good('PATCH','/settings/paymentInfo',{'version':edited['version'],'value':pinfo['value']})
# Ubicación del cliente para el reparto.
cl=good('POST','/customers',{'name':'Reparto '+u})
cl=good('PATCH',f"/customers/{cl['id']}/location",{'latitude':14.0723,'longitude':-87.1921,'address':'Frente a la pulpería azul'})
check(cl['latitude']==14.0723 and cl['address']=='Frente a la pulpería azul','customer delivery spot is saved')
check(call('PATCH',f"/customers/{cl['id']}/location",{'latitude':14.07,'longitude':None})[0]==400,'spot needs both coordinates')
check(call('PATCH',f"/customers/{cl['id']}/location",{'latitude':95,'longitude':10})[0]==400,'coordinates must be valid')
check(good('POST','/geo/resolve',{'url':'https://www.google.com/maps/place/X/@14.1,-87.2,15z'})=={'latitude':14.1,'longitude':-87.2},'maps link gives coordinates')
check(call('POST','/geo/resolve',{'url':'https://evil.example/x'})[0]==400,'other hosts are never fetched')
cl=good('PATCH',f"/customers/{cl['id']}/location",{'latitude':None,'longitude':None})
check(cl['latitude'] is None and cl['address']=='Frente a la pulpería azul','spot can be cleared, address kept')
# Unidades: solo las libras llevan medias.
jar=good('POST','/products',{'name':'Miel bote '+u,'salePrice':'180','estimatedCost':'120','defaultSupplierId':s['id'],'unit':'bote'})
check(jar['unit']=='bote','product keeps its unit')
check(call('POST','/products',{'name':'X '+u,'salePrice':'1','estimatedCost':'1','defaultSupplierId':s['id'],'unit':'kilo'})[0]==400,'unknown unit is rejected')
c6=good('POST','/rounds',{'name':'Unidades '+u,'opensAt':'2026-10-06T00:00:00Z','closesAt':'2026-10-12T00:00:00Z'})
jline={'productId':jar['id'],'supplierId':s['id'],'unitPrice':'180'}
check(call('POST','/orders',{'roundId':c6['id'],'customerId':c['id'],'items':[{**jline,'quantity':'1.5'}]})[0]==400,'whole units cannot be ordered in halves')
oj=good('POST','/orders',{'roundId':c6['id'],'customerId':c['id'],'items':[{**jline,'quantity':'2'}]})
check(oj['total']=='360.00','whole units are priced per unit')
check(call('POST','/purchases',{'id':uid(),'roundId':c6['id'],'supplierId':s['id'],'orderedAt':'2026-10-06T10:00:00Z','items':[{'productId':jar['id'],'quantity':'2.5','quotedUnitCost':'120'}]})[0]==400,'whole units cannot be bought in halves')
bj=good('POST','/purchases',{'id':uid(),'roundId':c6['id'],'supplierId':s['id'],'orderedAt':'2026-10-06T10:00:00Z','items':[{'productId':jar['id'],'quantity':'3','quotedUnitCost':'120'}]})
check(call('POST',f"/purchases/{bj['id']}/receipts",{'id':uid(),'version':bj['version'],'receivedAt':'2026-10-06T12:00:00Z','invoice':'J '+u,'globalDiscount':'0','items':[{'purchaseItemId':bj['items'][0]['id'],'quantity':'1.5','unitCost':'120','unitDiscount':'0'}]})[0]==400,'whole units cannot be received in halves')
good('POST',f"/purchases/{bj['id']}/receipts",{'id':uid(),'version':bj['version'],'receivedAt':'2026-10-06T12:00:00Z','invoice':'J '+u,'globalDiscount':'0','items':[{'purchaseItemId':bj['items'][0]['id'],'quantity':'3','unitCost':'120','unitDiscount':'0'}]})
oj=next(o for o in good('GET',f"/orders?roundId={c6['id']}") if o['id']==oj['id'])
check(call('POST',f"/orders/{oj['id']}/deliveries",{'id':uid(),'version':oj['version'],'deliveredAt':'2026-10-06T13:00:00Z','items':[{'orderItemId':oj['items'][0]['id'],'quantity':'0.5'}]})[0]==400,'whole units cannot be delivered in halves')
check(call('PATCH',f"/products/{jar['id']}",{'unit':'bolsa'})[0]==400,'unit of a used product cannot change')
cy=next(x for x in good('GET','/statistics')['cycles'] if x['id']==c6['id'])
check(cy['quantityByUnit']=={'bote':'2'},'statistics count quantities per unit')
# Envío en ventas sin encargo.
sj=good('POST','/sales',{'id':uid(),'roundId':c6['id'],'soldAt':'2026-10-06T14:00:00Z','delivery':'DELIVERY','shippingFee':'25','items':[{'productId':jar['id'],'quantity':'1','unitPrice':'180'}],'payment':{'amount':'205','method':'CASH'}})
check(sj['total']=='205.00' and sj['shippingFee']=='25.00' and sj['paymentStatus']=='PAID','walk-in sale can carry a shipping fee')
check(call('POST','/sales',{'id':uid(),'roundId':c6['id'],'soldAt':'2026-10-06T14:00:00Z','delivery':'PICKUP','shippingFee':'25','items':[{'productId':jar['id'],'quantity':'1','unitPrice':'180'}]})[0]==400,'pickup sale cannot carry a fee')
check(call('PATCH',f"/sales/{sj['id']}",{'version':sj['version'],'delivery':'PICKUP','items':[{'productId':jar['id'],'quantity':'1','unitPrice':'180'}]})[0]==400,'dropping the fee below what was paid is rejected')
sj=good('PATCH',f"/sales/{sj['id']}",{'version':sj['version'],'delivery':'DELIVERY','shippingFee':'25','items':[{'productId':jar['id'],'quantity':'1','unitPrice':'180'}]})
check(sj['total']=='205.00','editing a sale keeps its shipping')
# Combos: receta mixta, armado con costo real, deshacer y venta.
mk=lambda n,unit,cost,price:good('POST','/products',{'name':n+' '+u,'salePrice':price,'estimatedCost':cost,'defaultSupplierId':s['id'],'unit':unit})
rosq=mk('Rosquilla','unidad','4','6'); ques=mk('Quesadilla','unidad','6','9'); combo=mk('Combo mixto','bolsa','50','120')
recipe=lambda comps:call('PATCH',f"/products/{combo['id']}/components",{'components':comps})
check(recipe([{'componentId':combo['id'],'quantity':'1'}])[0]==400,'a combo cannot contain itself')
check(recipe([{'componentId':rosq['id'],'quantity':'2.5'}])[0]==400,'recipe respects component units')
good('PATCH',f"/products/{combo['id']}/components",{'components':[{'componentId':rosq['id'],'quantity':'5'},{'componentId':ques['id'],'quantity':'5'}]})
check(call('PATCH',f"/products/{rosq['id']}/components",{'components':[{'componentId':combo['id'],'quantity':'1'}]})[0]==400,'a component cannot become a combo')
check(next(p for p in good('GET','/products') if p['id']==combo['id'])['components'][0]['quantity'] in ('5','5.000'),'products expose their recipe')
cR=good('POST','/rounds',{'name':'Combos '+u,'opensAt':'2026-10-06T00:00:00Z','closesAt':'2026-10-12T00:00:00Z'})
bc=good('POST','/purchases',{'id':uid(),'roundId':cR['id'],'supplierId':s['id'],'orderedAt':'2026-10-06T08:00:00Z','items':[{'productId':rosq['id'],'quantity':'12','quotedUnitCost':'4'},{'productId':ques['id'],'quantity':'10','quotedUnitCost':'6'}]})
good('POST',f"/purchases/{bc['id']}/receipts",{'id':uid(),'version':bc['version'],'receivedAt':'2026-10-06T09:00:00Z','invoice':'PAN '+u,'globalDiscount':'0','items':[{'purchaseItemId':i['id'],'quantity':i['quantity'],'unitCost':i['quotedUnitCost'],'unitDiscount':'0'} for i in bc['items']]})
freeOf=lambda pid:sum(float(l['available']) for l in good('GET','/inventory') if l['productId']==pid)
assemble=lambda q,aid=None:call('POST','/assemblies',{'id':aid or uid(),'roundId':cR['id'],'comboId':combo['id'],'quantity':q,'date':'2026-10-06T10:00:00Z'})
code,out=assemble('3')
check(code==400 and 'Rosquilla' in out['message'],'assembly needs enough of every component')
a1=uid();code,out=assemble('1',a1)
check(code in (200,201) and out['unitCost']=='50.00' and freeOf(rosq['id'])==7 and freeOf(combo['id'])==1,'assembly turns components into a costed combo lot')
good('DELETE',f"/assemblies/{a1}")
check(freeOf(rosq['id'])==12 and freeOf(ques['id'])==10 and freeOf(combo['id'])==0,'undoing an assembly returns the components')
a2=uid();assemble('2',a2);assemble('2',a2)
check(freeOf(combo['id'])==2 and freeOf(ques['id'])==0,'assembly retry does not build twice')
check(all(p['kind']=='PURCHASE' for p in good('GET',f"/purchases?roundId={cR['id']}")),'assemblies are not listed as supplier purchases')
led=good('GET','/finance/ledger?month=2026-10')
check(not any(l['description'].startswith('Factura Armado') for l in led['lines']),'assemblies are not expenses')
sc=good('POST','/sales',{'id':uid(),'roundId':cR['id'],'soldAt':'2026-10-06T12:00:00Z','items':[{'productId':combo['id'],'quantity':'1','unitPrice':'120'}]})
pc=next(x for x in next(c for c in good('GET','/statistics')['cycles'] if c['id']==cR['id'])['productCosts'] if x['productId']==combo['id'])
check(pc['unitCost']=='50.00' and pc['unit']=='bolsa','combo sale is costed with its assembly cost')
check(call('DELETE',f"/assemblies/{a2}")[0]==409,'a used assembly cannot be undone')
check(next(a for a in good('GET',f"/assemblies?roundId={cR['id']}") if a['id']==a2)['undoable'] is False,'assembly list says it can no longer be undone')
cE=good('POST','/rounds',{'name':'Encargo combo '+u,'opensAt':'2026-10-06T00:00:00Z','closesAt':'2026-10-12T00:00:00Z'})
good('POST','/orders',{'roundId':cE['id'],'customerId':c['id'],'items':[{'productId':combo['id'],'supplierId':s['id'],'quantity':'2','unitPrice':'120'}]})
rowsE={i['productId']:i for g in good('GET',f"/rounds/{cE['id']}/purchase-summary")['groups'] for i in g['items']}
check(combo['id'] not in rowsE and rowsE[rosq['id']]['quantity'] in ('10','10.000') and rowsE[ques['id']]['pendingToBuy'] in ('10','10.000'),'an encargo of combos asks to buy their components')
# Categorías de producto.
pcats=good('GET','/product-categories')
check({'Lácteos','Panadería','Miel','Suplementos'} <= {c['name'] for c in pcats},'starting categories exist')
newcat=good('POST','/product-categories',{'name':'Bebidas '+u})
check(call('POST','/product-categories',{'name':'bebidas '+u.upper()})[0]==409,'category names are unique')
pan=next(c for c in pcats if c['name']=='Panadería')
good('PATCH',f"/products/{rosq['id']}",{'categoryId':pan['id']})
good('PATCH',f"/products/{combo['id']}",{'categoryId':pan['id']})
check(call('PATCH',f"/products/{rosq['id']}",{'categoryId':str(uuid.uuid4())})[0]==400,'unknown category is rejected')
check(next(p for p in good('GET','/products') if p['id']==rosq['id'])['category']['name']=='Panadería','products carry their category')
good('PATCH',f"/products/{ques['id']}",{'categoryId':newcat['id']})
check(call('DELETE',f"/product-categories/{newcat['id']}")[0]==409,'a category with products cannot be deleted')
good('PATCH',f"/products/{ques['id']}",{'categoryId':None})
good('DELETE',f"/product-categories/{newcat['id']}")
cyc=next(c for c in good('GET','/statistics')['cycles'] if c['id']==cR['id'])
pr=next(x for x in cyc['categories'] if x['name']=='Panadería')
check(pr['sales']=='120.00' and pr['cost']=='50.00' and pr['profit']=='70.00','statistics show sales, cost and profit per category')
good('POST','/auth/logout')
print(json.dumps({'passed':len(checks),'checks':checks},ensure_ascii=False,indent=2))
